version: '3'

services:

    db:
        image: mysql:5.7.16
        container_name: dbmysql     
        restart: always
        volumes:
            - ./.sqldata:/var/lib/mysql
        ports:
            - 33066:3306
        environment:
            MYSQL_DATABASE: admin
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
        command: --default-authentication-plugin=mysql_native_password

    dcDjango:
        build: .
        image: dc_django
        container_name: dc_django    
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db            
#        command: tail -f /dev/null                
        command: bash -c '
                cp -r /tmp/admin/* /code/ -n &&
                python3 /code/manage.py migrate &&
                python3 /code/manage.py runserver 0.0.0.0:8000
                '
